export const SCHEDULE_DATA = [
  {
    day: 1,
    date: "Jan 22, Thursday",
    title: "The Awakening",
    events: [
      {
        time: "11:00 AM - 12:00 PM",
        title: "Ethos human form creation",
        location: "Ethos Ground",
        category: "General",
        description: "Formation of human ethos logo.",
      },
      {
        time: "10:00 AM - 2:00 PM",
        title: "E Stratega",
        location: "Consiglio",
        category: "Management",
        description: "Strategic management competition by Consiglio.",
      },
      {
        time: "10:00 AM - 5:00 PM",
        title: "Adwiteeya 3.0",
        location: "IEC",
        category: "Management",
        description: "Entrepreneurship challenge by IEC.",
      },
      {
        time: "10:00 AM - 5:00 PM",
        title: "Hack-A-thon 6.0",
        location: "IEC",
        category: "Technical",
        description: "Coding marathon by IEC.",
      },
      {
        time: "11:00 AM - 2:00 PM",
        title: "Policy Crosswords",
        location: "Neeti",
        category: "Management",
        description: "Public policy crossword challenge by Neeti.",
      },
      {
        time: "11:00 AM - 2:00 PM",
        title: "Ops'timato",
        location: "Sigmato",
        category: "Management",
        description: "Operations management simulation by Sigmato.",
      },
      {
        time: "12:00 PM - 2:00 PM",
        title: "DataViz 3.0",
        location: "Rsquared",
        category: "Technical",
        description: "Data visualization competition by Rsquared.",
      },
      {
        time: "12:00 PM - 3:00 PM",
        title: "UnRavel 6.0",
        location: "Rsquared",
        category: "Technical",
        description: "Analytics case study by Rsquared.",
      },
      {
        time: "12:00 PM - 2:00 PM",
        title: "Globiz",
        location: "OIR",
        category: "Management",
        description: "International business quiz by OIR.",
      },
      {
        time: "12:00 PM - 6:00 PM",
        title: "Singing Souls and Tihai",
        location: "Kalakriti",
        category: "Cultural",
        description: "Music and dance performances by Kalakriti.",
      },
      {
        time: "2:00 PM - 5:00 PM",
        title: "The Ultimate PM",
        location: "AlphaBeta",
        category: "Management",
        description: "Product management showdown by AlphaBeta.",
      },
      {
        time: "2:00 PM - 3:30 PM",
        title: "Echo - Bing and Brush",
        location: "ECHO",
        category: "Cultural",
        description: "Art and creativity workshop by ECHO.",
      },
      {
        time: "2:00 PM - 5:30 PM",
        title: "Guess-It-Mate",
        location: "Consiglio",
        category: "Management",
        description: "Guesstimate challenge by Consiglio.",
      },
      {
        time: "2:00 PM - 5:30 PM",
        title: "HRAlchemy",
        location: "HRidya",
        category: "Management",
        description: "HR case study competition by HRidya.",
      },
      {
        time: "2:30 PM - 6:00 PM",
        title: "Technovate 1.0",
        location: "Technospark",
        category: "Technical",
        description: "Innovation showcase by Technospark.",
      },
      {
        time: "3:30 PM - 5:30 PM",
        title: "CineCraft",
        location: "PR & Media",
        category: "Cultural",
        description: "Short film contest by PR & Media.",
      },
      {
        time: "4:00 PM - 5:30 PM",
        title: "Kartavya",
        location: "ECHO",
        category: "Social",
        description: "Social responsibility initiative by ECHO.",
      },
      {
        time: "5:30 PM - 8:00 PM",
        title: "Style-O-Holic",
        location: "Magnum Opus",
        category: "Cultural",
        description: "Fashion show event by Magnum Opus.",
      },
      {
        time: "8:00 PM - 9:00 PM",
        title: "Stand Up Comedy",
        location: "Auditorium",
        category: "Cultural",
        description: "Late night comedy show.",
      },
      {
        time: "10:00 PM - 2:00 AM",
        title: "Concert Night",
        location: "Main Ground",
        category: "Cultural",
        description: "Live musical performance.",
      },
    ],
  },
  {
    day: 2,
    date: "Jan 23, Friday",
    title: "Cosmic Voyage",
    events: [
      {
        time: "9:00 AM - 4:00 PM",
        title: "Mela Quiz",
        location: "Sahityam",
        category: "Cultural",
        description: "Culture quiz by Sahityam.",
      },
      {
        time: "9:00 AM - 4:00 PM",
        title: "The Cryptic Chase",
        location: "Sahityam",
        category: "Cultural",
        description: "Treasure hunt by Sahityam.",
      },
      {
        time: "10:00 AM - 6:00 PM",
        title: "Mudra Bazaar",
        location: "BnB",
        category: "Management",
        description: "Finance simulation by BnB.",
      },
      {
        time: "10:00 AM - 6:00 PM",
        title: "StocksSprint",
        location: "BnB",
        category: "Management",
        description: "Stock trading challenge by BnB.",
      },
      {
        time: "11:00 AM - 2:00 PM",
        title: "BrandBazi 8.0",
        location: "Emporia",
        category: "Management",
        description: "Brand quiz by Emporia.",
      },
      {
        time: "12:00 PM - 2:00 PM",
        title: "Ops'Ecape Room",
        location: "Sigmato",
        category: "Management",
        description: "Operations escape room by Sigmato.",
      },
      {
        time: "2:00 PM - 5:00 PM",
        title: "Product Decipher",
        location: "AlphaBeta",
        category: "Management",
        description: "Product challenge by AlphaBeta.",
      },
      {
        time: "2:00 PM - 5:30 PM",
        title: "HRDiscourse",
        location: "HRidya",
        category: "Management",
        description: "HR panel discussion by HRidya.",
      },
      {
        time: "2:30 PM - 6:00 PM",
        title: "BGMI X Codm Showdown",
        location: "Technospark",
        category: "Technical",
        description: "Esports tournament by Technospark.",
      },
      {
        time: "3:00 PM - 6:00 PM",
        title: "Scavenger Hunt",
        location: "PR & Media",
        category: "Cultural",
        description: "Campus scavenger hunt by PR & Media.",
      },
      {
        time: "4:00 PM - 6:00 PM",
        title: "Pronigma 7.0",
        location: "Emporia",
        category: "Management",
        description: "Product riddle challenge by Emporia.",
      },
      {
        time: "5:00 PM - 7:00 PM",
        title: "Sanskriti Sangam",
        location: "Magnum Opus",
        category: "Cultural",
        description: "Cultural showcase by Magnum Opus.",
      },
      {
        time: "8:00 PM - 9:00 PM",
        title: "StandUp Comedy",
        location: "Auditorium",
        category: "Cultural",
        description: "Comedy night.",
      },
      {
        time: "10:00 PM - 2:00 AM",
        title: "Concert Night",
        location: "Main Ground",
        category: "Cultural",
        description: "Headlining musical performance.",
      },
    ],
  },
  {
    day: 3,
    date: "Jan 24, Saturday",
    title: "The Ascension",
    events: [
      {
        time: "2:00 PM - 4:00 PM",
        title: "Unscripted Frames",
        location: "Pixel",
        category: "Cultural",
        description: "Photography competition by Pixel.",
      },
      {
        time: "4:00 PM - 6:00 PM",
        title: "The Final Cut",
        location: "Pixel",
        category: "Cultural",
        description: "Video editing contest by Pixel.",
      },
      {
        time: "4:00 PM - 5:00 PM",
        title: "Valedictory Ceremony",
        location: "Auditorium",
        category: "General",
        description: "Prize distribution and closing.",
      },
      {
        time: "7:00 PM - 8:00 PM",
        title: "Harmonix",
        location: "Main Ground",
        category: "Cultural",
        description: "Musical fusion performance.",
      },
      {
        time: "8:00 PM - 9:00 PM",
        title: "Synergy",
        location: "Main Ground",
        category: "Cultural",
        description: "Dance performance.",
      },
      {
        time: "9:00 PM - 2:00 AM",
        title: "DJ Night",
        location: "Main Ground",
        category: "Cultural",
        description: "EDM night finale.",
      },
    ],
  },
];
