// src/config/scheduleData.ts

export const SCHEDULE_DATA = [
  {
    day: 1,
    date: "Jan 22, Thursday",
    title: "The Awakening",
    events: [
      {
        time: "10:00 AM",
        title: "E Stratega",
        location: "Consiglio",
        category: "Management",
        description: "Strategic management competition.",
      },
      {
        time: "10:00 AM",
        title: "Adwiteeya 3.0",
        location: "IEC",
        category: "Management",
        description: "Entrepreneurship challenge.",
      },
      {
        time: "10:00 AM",
        title: "Hack-A-thon 6.0",
        location: "IEC",
        category: "Technical",
        description: "Coding and development marathon.",
      },
      {
        time: "11:00 AM",
        title: "Policy Crosswords",
        location: "Neeti",
        category: "Management",
        description: "Public policy crossword challenge.",
      },
      {
        time: "11:00 AM",
        title: "Ops'timato",
        location: "Sigmato",
        category: "Management",
        description: "Operations management simulation.",
      },
      {
        time: "12:00 PM",
        title: "Inaugural Ceremony",
        location: "Auditorium",
        category: "General",
        description: "Official opening of ETHOS '26.",
      },
      {
        time: "12:00 PM",
        title: "DataViz 3.0",
        location: "Rsquared",
        category: "Technical",
        description: "Data visualization competition.",
      },
      {
        time: "12:00 PM",
        title: "UnRavel 6.0",
        location: "Rsquared",
        category: "Technical",
        description: "Analytics case study.",
      },
      {
        time: "12:00 PM",
        title: "The Ultimate PM",
        location: "AlphaBeta",
        category: "Management",
        description: "Product management showdown.",
      },
      {
        time: "12:00 PM",
        title: "Globiz",
        location: "OIR",
        category: "Management",
        description: "International business quiz.",
      },
      {
        time: "2:00 PM",
        title: "Singing Souls and Tihai",
        location: "Kalakriti",
        category: "Cultural",
        description: "Music and dance performances.",
      },
      {
        time: "2:00 PM",
        title: "Echo - Bing and Brush",
        location: "ECHO",
        category: "Cultural",
        description: "Art and creativity workshop.",
      },
      {
        time: "2:00 PM",
        title: "Guess-It-Mate",
        location: "Consiglio",
        category: "Management",
        description: "Guesstimate challenge.",
      },
      {
        time: "2:00 PM",
        title: "HRAlchemy",
        location: "HRidya",
        category: "Management",
        description: "HR case study competition.",
      },
      {
        time: "2:30 PM",
        title: "Technovate 1.0",
        location: "Technospark",
        category: "Technical",
        description: "Innovation and technology showcase.",
      },
      {
        time: "3:30 PM",
        title: "CineCraft",
        location: "PR & Media",
        category: "Cultural",
        description: "Short film making contest.",
      },
      {
        time: "4:00 PM",
        title: "Kartavya",
        location: "ECHO",
        category: "Social",
        description: "Social responsibility initiative.",
      },
      {
        time: "5:30 PM",
        title: "Style-O-Holic",
        location: "Magnum Opus",
        category: "Cultural",
        description: "Fashion show event.",
      },
      {
        time: "8:00 PM",
        title: "Concert Night",
        location: "Main Ground",
        category: "Cultural",
        description: "Musical performance by star artist.",
      },
    ],
  },
  {
    day: 2,
    date: "Jan 23, Friday",
    title: "Cosmic Voyage",
    events: [
      {
        time: "9:00 AM",
        title: "Mela Quiz",
        location: "Sahityam",
        category: "Cultural",
        description: "Literature and culture quiz.",
      },
      {
        time: "9:00 AM",
        title: "The Cryptic Chase",
        location: "Sahityam",
        category: "Cultural",
        description: "Treasure hunt with literary clues.",
      },
      {
        time: "10:00 AM",
        title: "Mudra Bazaar",
        location: "BnB",
        category: "Management",
        description: "Finance and trading simulation.",
      },
      {
        time: "10:00 AM",
        title: "StocksSprint",
        location: "BnB",
        category: "Management",
        description: "Stock market trading sprint.",
      },
      {
        time: "12:00 PM",
        title: "Ops'Ecape Room",
        location: "Sigmato",
        category: "Management",
        description: "Operations-themed escape room.",
      },
      {
        time: "12:00 PM",
        title: "Product Decipher",
        location: "AlphaBeta",
        category: "Management",
        description: "Product deconstruction challenge.",
      },
      {
        time: "2:00 PM",
        title: "HRDiscourse",
        location: "HRidya",
        category: "Management",
        description: "Panel discussion on HR trends.",
      },
      {
        time: "2:00 PM",
        title: "BGMI X Codm Showdown",
        location: "Technospark",
        category: "Technical",
        description: "Mobile gaming tournament.",
      },
      {
        time: "2:30 PM",
        title: "Scavenger Hunt",
        location: "PR & Media",
        category: "Cultural",
        description: "Campus-wide scavenger hunt.",
      },
      {
        time: "3:00 PM",
        title: "BrandBazi 8.0",
        location: "Emporia",
        category: "Management",
        description: "Marketing and branding quiz.",
      },
      {
        time: "4:00 PM",
        title: "Pronigma 7.0",
        location: "Emporia",
        category: "Management",
        description: "Product riddle challenge.",
      },
      {
        time: "4:00 PM",
        title: "Sanskriti Sangam",
        location: "Magnum Opus",
        category: "Cultural",
        description: "Cultural integration showcase.",
      },
      {
        time: "5:00 PM",
        title: "StandUp Comedy",
        location: "Auditorium",
        category: "Cultural",
        description: "Comedy night featuring guest artist.",
      },
      {
        time: "8:00 PM",
        title: "Concert Night",
        location: "Main Ground",
        category: "Cultural",
        description: "Headlining musical performance.",
      },
    ],
  },
  {
    day: 3,
    date: "Jan 24, Saturday",
    title: "The Ascension",
    events: [
      {
        time: "2:00 PM",
        title: "Unscripted Frames",
        location: "Pixel",
        category: "Cultural",
        description: "Photography competition.",
      },
      {
        time: "4:00 PM",
        title: "The Final Cut",
        location: "Pixel",
        category: "Cultural",
        description: "Video editing showdown.",
      },
      {
        time: "4:00 PM",
        title: "Valedictory Ceremony",
        location: "Auditorium",
        category: "General",
        description: "Prize distribution and closing address.",
      },
      {
        time: "5:00 PM",
        title: "Closing Ceremony",
        location: "Auditorium",
        category: "General",
        description: "Official closing by Convener & Co-Convener.",
      },
      {
        time: "7:00 PM",
        title: "Harmonix",
        location: "Main Ground",
        category: "Cultural",
        description: "Musical fusion performance.",
      },
      {
        time: "8:00 PM",
        title: "Synergy and Kalakriti",
        location: "Main Ground",
        category: "Cultural",
        description: "Collaborative dance and art show.",
      },
      {
        time: "9:00 PM",
        title: "DJ Night",
        location: "Festival Ground",
        category: "Cultural",
        description: "EDM night finale.",
      },
    ],
  },
];
